### ISSUE TITLE
Highest Score

### ISSUE THREAD

**Issue by dandavies23** [dandavies23/smoothie-moves#38]
AG " scoreboard in that case you have to maintain a local storage you have to do it via **local storage**"

**Comment by Y0ursTruly** [comment]
this seems achievable

**Comment by dandavies23** [comment]
Just looking at this: https://michael-karen.medium.com/how-to-save-high-scores-in-local-storage-7860baca9d68

**Comment by Y0ursTruly** [comment]
oh.. we aren't storing scores :{
