### ISSUE TITLE
Watch pointer to turn into finger to show it's clickable

### ISSUE THREAD

**Issue by dandavies23** [dandavies23/smoothie-moves#49]

**Comment by Y0ursTruly** [comment]
you mean you want the mouse look changed?

**Comment by dandavies23** [comment]
Yes to a hand :) going to get on this first thing tomorrow. Also my testers (nieces and nephews) tapped in certain areas and selected text which interfered slightly with gameplay. Will take a look at that also - deadline is midday for the project. Anything not sorted by then will go into v2 and v3 :)

**Comment by dandavies23** [comment]
.pointer       { cursor: pointer; }
